version: '3.8'

services:
  app:
    container_name: help-hive
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/local/help-hive
    env_file:
      - .env
    ports:
      - "5000:5000"
    command: sh -c "npx prisma generate && yarn start:dev"
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: "postgres:17"
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - help-hive-db:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  help-hive-db:

networks:
  app-network:
    driver: bridge
