name: CI/CD Pipleline for the application
run-name: ${{ github.actor }} is testing out CI/CD Pipleline for the application 🚀
on:
  push:
    branches:
      - main
      - stage
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploying the application..."
          echo "Deployed the application successfully!"
